# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sk-api}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Georg Leciejewski"]
  s.date = %q{2010-11-07}
  s.description = %q{Interact with SalesKing}
  s.email = %q{gl@salesking.eu}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "Manifest",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/patches/README",
     "lib/patches/ar2/base.rb",
     "lib/patches/ar2/validations.rb",
     "lib/patches/ar3/base.rb",
     "lib/patches/ar3/validations.rb",
     "lib/resources/address.rb",
     "lib/resources/base.rb",
     "lib/resources/client.rb",
     "lib/resources/credit_note.rb",
     "lib/resources/invoice.rb",
     "lib/resources/line_item.rb",
     "lib/resources/product.rb",
     "lib/sk_api.rb",
     "lib/utils/field_map.rb",
     "lib/utils/serializer.rb",
     "sk-api.gemspec",
     "spec/resources/client_spec.rb",
     "spec/resources/credit_note_spec.rb",
     "spec/resources/invoice_spec.rb",
     "spec/resources/product_spec.rb",
     "spec/spec_helper.rb",
     "spec/utils/field_map_spec.rb",
     "tasks/sk_api_tasks.rake",
     "vendor/jsonschema-1.0.0/README.rdoc",
     "vendor/jsonschema-1.0.0/Rakefile",
     "vendor/jsonschema-1.0.0/lib/jsonschema.rb",
     "vendor/jsonschema-1.0.0/ruby-jsonschema.gemspec",
     "vendor/jsonschema-1.0.0/test/jsonschema_test.rb"
  ]
  s.homepage = %q{http://github.com/salesking/sk-api}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Interact with SalesKing}
  s.test_files = [
    "spec/resources/client_spec.rb",
     "spec/resources/credit_note_spec.rb",
     "spec/resources/invoice_spec.rb",
     "spec/resources/product_spec.rb",
     "spec/spec_helper.rb",
     "spec/utils/field_map_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

